name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: continuous integration
    runs-on: ledgerhq-shared-small
    timeout-minutes: 60
    steps:

      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@v4

      - name: Install linters
        timeout-minutes: 10
        run: |
          python -m pip install --upgrade pip
          pip install -i https://${{ secrets.PYPI_DEPLOY_TOKEN}}:@pypi.fury.io/ledger/ erc7730_hackathon
