name: continuous integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: continuous integration
    runs-on: ledgerhq-shared-small
    timeout-minutes: 60
    steps:
      - name: Login to Ledger Artifactory
        id: jfrog-login
        uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1

      - name: Checkout
        timeout-minutes: 10
        uses: actions/checkout@v4

      - name: URL encode JFrog credentials
        shell: bash
        run: |
          echo JFROG_USER_ENCODED=$(echo -n $JFROG_USER | jq -sRr @uri) >> $GITHUB_ENV
          echo JFROG_TOKEN_ENCODED=$(echo -n JFROG_TOKEN | jq -sRr @uri) >> $GITHUB_ENV

      - name: Install linters
        timeout-minutes: 10
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -i https://${{ env.JFROG_USER_ENCODED }}:${{ env.JFROG_TOKEN }}@jfrog.ledgerlabs.net/artifactory/api/pypi/vault-pypi-prod-green erc7730_hackathon
